[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"